# Generated by Django 5.0.6 on 2024-06-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_info',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
